### PR TITLE
fix: adaptive thinking for Opus 4.6/4.7 & Sonnet 4.6

### LINKED ISSUE #9: Opus 4.7 shows no thinking in pi
Opus 4.7 rejects the legacy `thinking: { type: "enabled" }` shape
entirely (HTTP 400). Opus 4.6 and Sonnet 4.6 still accept it but
adaptive is recommended and produces better output.

### PR DESCRIPTION
**Pull request by micuintus**
Fixes #9.

Three changes, minimal:

1. SDK update: `^0.2.32` → `^0.2.116`. 
2. For Opus 4.6/4.7 and Sonnet 4.6, send
   `thinking: { type: "adaptive", display: "summarized" }` + `effort`
   mapped from pi's `reasoning` level. Other models keep
   `maxThinkingTokens` untouched.
3. Resolve `claude` from `@anthropic-ai/claude-agent-sdk-<plat>-<arch>`
   via `import.meta.resolve` and pass `pathToClaudeCodeExecutable`.

Model detection uses substring checks, same pattern used elsewhere in
the file. Can swap for capability metadata if upstream pi ever exposes
one.

Verified in pi TUI: Opus 4.7 + induction-proof prompt now renders
thinking summary.

### CODE REVIEW

File: index.ts [hunk 1]
```diff
@@ -788,6 +789,37 @@ function mapThinkingTokens(
...
+
+const PI_LEVEL_TO_EFFORT: Record<ThinkingLevel, EffortLevel> = {
+	minimal: "low",
+	low: "low",
+	medium: "medium",
+	high: "high",
+	xhigh: "xhigh",
+};
+
+function resolveClaudeCodeExecutable(): string | undefined {
```
Comment (prateekmedia) [inline index.ts]: Why is this needed now when it wasn't before?

Comment (micuintus) [reply index.ts]: This is only needed because of the SDK bump in this PR. From 0.2.111 onward, `cli.js` no longer ships in `@anthropic-ai/claude-agent-sdk`; the binary moved to platform packages like `@anthropic-ai/claude-agent-sdk-darwin-arm64`. Without `pathToClaudeCodeExecutable`, query() throws `Claude Code executable not found at .../cli.js`. Happy to add a comment in the code if useful.

Comment (prateekmedia) [reply index.ts]: More docs would help, also I checked https://github.com/agentclientprotocol/claude-agent-acp/blob/e30f0e5ba03e830636b98b4804b177004318af60/src/acp-agent.ts#L265, they have separate handling for linux, check if we need to do that.

Comment (micuintus) [reply index.ts]: Done. Added JSDoc and inline comments explaining why we bypass SDK auto-resolution.

Also adopted the `createRequire`-bound-to-SDK pattern from that reference, with Linux musl-first then glibc fallback, `.exe` on Windows, and `CLAUDE_CODE_EXECUTABLE` env override.

File: index.ts [hunk 2]
```diff
@@ -900,14 +959,20 @@ function streamClaudeAgentSdk(model: Model<any>, context: Context, options?: Sim
...
 				...(settingSources ? { settingSources } : {}),
 				...(extraArgs ? { extraArgs } : {}),
 				...(mcpServers ? { mcpServers } : {}),
 			};
 
-			const maxThinkingTokens = mapThinkingTokens(options?.reasoning, model.id, options?.thinkingBudgets);
-			if (maxThinkingTokens != null) {
-				queryOptions.maxThinkingTokens = maxThinkingTokens;
+			if (options?.reasoning && supportsAdaptiveThinking(model.id)) {
+				queryOptions.thinking = { type: "adaptive", display: "summarized" } satisfies ThinkingConfig;
```
Comment (prateekmedia) [inline index.ts:971]: A quick question, will this "adaptive" cause any issues. Not sure what exactly is it supposed to do. Like If I have low reasoning or high reasoning, what difference will it make by always setting adaptive thinking here?

File: index.ts [hunk 3]
```diff
@@ -788,6 +789,63 @@ function mapThinkingTokens(
...
+		modelId.includes("sonnet-4.6")
+	);
+}
+
+const PI_LEVEL_TO_EFFORT: Record<ThinkingLevel, EffortLevel> = {
+	minimal: "low",
+	low: "low",
+	medium: "medium",
+	high: "high",
+	xhigh: "xhigh",
```
Comment (prateekmedia) [inline index.ts]: xhigh might not be available in custom claude agent sdk implementation as pi only gives xhigh for claude anthropic provider.

Comment (prateekmedia) [reply index.ts]: We were mapping one reasoning lower, so minimal was low, low was medium, medium was high and high was acting as xhigh, cause xhigh wasn't present for our provider.

File: index.ts (hunk 2 above)
Comment (micuintus) [reply index.ts:971]: Adaptive lets the model decide per prompt whether to think and how much.

`display: "summarized"` is the part that actually makes thinking stream to the client. Without it the model thinks silently and we see nothing, which is the bug this PR fixes.

It's also not really optional for these three: the API rejects the legacy `thinking.type: "enabled"` shape for Opus 4.7 outright (HTTP 400), and recommends adaptive for Opus 4.6 and Sonnet 4.6.

File: index.ts (hunk 3 above)
Comment (micuintus) [reply index.ts]: Good catch. Anthropic SDK accepts `low | medium | high | xhigh | max` (also this is how they document it)

**Review by prateekmedia — APPROVED** [review]

File: index.ts (hunk 3 above)
Comment (micuintus) [reply index.ts]: So, instead of mapping the "GPT style" thinking levels that Pi has as a general concept at the moment, I believe Pi should switch to exposing the model specific thinking levels, something like this:

https://github.com/badlogic/pi-mono/issues/3208

Comment (prateekmedia) [reply index.ts]: Yeah, they should let provider decide instead of hardcoding.
